### ISSUE TITLE
Bug - Spinning but not Downloading

### ISSUE THREAD

**Issue by mojohajer** [Tenpi/soundcloud-download#12] opened 2021-08-19 04:56 UTC
Hi, 

I am trying to download songs from my private playlists on soundcloud. After the initial install, I went to my first playlist (158 tracks), hit download, and it worked quite quickly - after spinning for a few minutes, the downloads began accumulating rapidly in the footer of my chrome window. I then went to a different, much shorter playlist (13 tracks), and found that after hitting download, the arrows just kept spinning in circles for 10+ minutes. It eventually just gave up and revealed the download button again, but nothing had downloaded. I then tried on a few other playlists as well and am getting the same issue.

Any tips?

Side note - a progress indicator would be nice, especially for larger playlists.

Thanks,
Jack

**Comment by mojohajer** [comment] 2021-08-19 05:08
Ah, it gets stuck on the Go+ tracks. If not downloadable, can you bypass?

**Comment by Tenpi** [comment] 2021-08-19 06:12
> Ah, it gets stuck on the Go+ tracks. If not downloadable, can you bypass?

Would you mind posting an example of a track that doesn't download? I will see if I'm able to add support for it. I should also change it to download each track one at a time instead of all at once, I think that would provide better feedback that the extension is working.

**Comment by Tenpi** [comment] 2021-08-19 06:58
The newest version, `v0.3.1`, downloads tracks one at a time and should skip any tracks with errors.

**Comment by mojohajer** [comment] 2021-08-19 08:27
I have the v0.3.1 downloaded, but it turns out I was falsely attributing
the error to the Go+ tracks.

I installed another soundcloud downloader (
https://addoncrop.com/soundcloud-music-downloader/) when I found that yours
was not working, and ran into the same issue. This other extension
displayed an error message related to the URL not being recognized. So I
tried the following and both extensions began to work:

1. navigating to the playlist
2. hitting "copy link"
3. pasting that link into the URL
--> for instance, this changed the URL from:
https://soundcloud.com/user-462503469/sets/flowga
----------------------------------------------------> to:
https://soundcloud.com/user-462503469/sets/flowga/s-wX74wOzg76L
4. then hitting download

Without this weird string appended to the URL, something doesn't work.

There are a few other people reporting that they are having issues with the
extension as well, and I don't think it's user error.

I hope this helps you debug.

Jack

**Comment by mojohajer** [comment] 2021-08-19 08:33
Also, here's an individual track that will not download for me:
https://soundcloud.com/camokrooked/camo-krooked-good-times-bad-times-bbc-radio1

The copy link trick does not work here (does not change the URL).

Jack

**Comment by Tenpi** [comment] 2021-08-19 16:05
> Without this weird string appended to the URL, something doesn't work. 

Can't reproduce with my own private playlists, my extension doesn't read the URL anyways (it obtains the tracks from the page source).

> Also, here's an individual track that will not download for me:
https://soundcloud.com/camokrooked/camo-krooked-good-times-bad-times-bbc-radio1

Update to `v0.3.2`. I added support for downloading the Go+ exclusive tracks.

**Comment by Tenpi** [comment] 2021-08-20 17:23
Closing as resolved.

**Closed by Tenpi** 2021-08-20 17:23 UTC
Labels: bug
